// Objetos de estilos y constantes visuales para el formulario de pedido

export const sStep = {
  wrap: { marginBottom: 14 },
  row: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  dots: { display: "flex", gap: 5 },
  dot: {
    width: 26,
    height: 26,
    borderRadius: "50%",
    border: "1.5px solid #d1d5db",
    background: "#f9fafb",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: 0,
  },
  dotOk: { background: "var(--verde)", border: "1.5px solid var(--verde)" },
  dotWarn: { background: "#fef3c7", border: "1.5px solid #f59e0b" },
  dotActivo: {
    border: "2px solid var(--verde)",
    background: "#fff",
    boxShadow: "0 0 0 3px var(--verde-bg)",
  },
  dotInactivo: { opacity: 0.35, cursor: "default" },
  pct: { fontSize: 12, fontWeight: 700, color: "var(--subtexto)" },
  track: {
    height: 5,
    borderRadius: 99,
    background: "#e5e7eb",
    overflow: "hidden",
  },
  fill: { height: "100%", borderRadius: 99, transition: "width 400ms ease" },
};

export const s = {
  titulo: {
    fontSize: 24,
    fontWeight: 800,
    color: "var(--verde)",
    margin: "2px 0 4px",
  },
  headerUsuarioWrap: { marginBottom: 8, paddingTop: 4 },
  selectorSemanaWrap: {
    display: "grid",
    gridTemplateColumns: "28px 1fr 28px",
    alignItems: "center",
    gap: 4,
    margin: "0 -10px 6px",
  },
  selectorSemana: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    scrollSnapType: "x mandatory",
    padding: "3px 2px 5px",
    scrollbarWidth: "none",
  },
  selectorArrow: {
    width: 28,
    height: 36,
    border: "none",
    borderRadius: 10,
    background: "#fff",
    color: "var(--verde)",
    fontSize: 24,
    fontWeight: 900,
    cursor: "pointer",
    boxShadow: "0 2px 8px rgba(15,23,42,0.08)",
  },
  selectorTab: {
    flex: "0 0 140px",
    minHeight: 58,
    padding: "7px 8px",
    borderRadius: 10,
    border: "1px solid #e2e8f0",
    background: "#f8fafc",
    color: "var(--subtexto)",
    cursor: "pointer",
    textAlign: "center",
    scrollSnapAlign: "center",
  },
  selectorTabActivo: {
    background: "#fff",
    color: "var(--verde)",
    boxShadow: "0 1px 6px rgba(0,0,0,0.10)",
  },
  fechaLimiteChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    background: "#fff8e1",
    border: "1px solid #ffe082",
    borderRadius: 20,
    padding: "4px 10px",
    fontSize: 12,
    fontWeight: 600,
    color: "#92400e",
    marginBottom: 12,
  },
  btnRepetir: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    width: "100%",
    background: "#f0fdf4",
    border: "1.5px solid #bbf7d0",
    borderRadius: 12,
    padding: "12px 16px",
    fontSize: 15,
    fontWeight: 700,
    color: "#166534",
    cursor: "pointer",
    marginBottom: 14,
  },
  estadoBanner: {
    textAlign: "center",
    padding: "60px 20px",
    background: "#fff",
    borderRadius: 16,
    margin: "24px 0",
  },
  diaCard: {
    background: "#fff",
    borderRadius: 14,
    border: "2px solid var(--borde)",
    overflow: "hidden",
  },
  diaHeader: {
    width: "100%",
    background: "none",
    border: "none",
    padding: "14px 14px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    textAlign: "left",
    cursor: "pointer",
    gap: 8,
  },
  selBadge: {
    display: "inline-block",
    fontSize: 13,
    background: "var(--verde-bg)",
    color: "var(--verde)",
    padding: "3px 10px",
    borderRadius: 20,
    fontWeight: 600,
  },
  selBadgeWarning: {
    display: "inline-block",
    fontSize: 13,
    background: "#fef3c7",
    color: "#92400e",
    padding: "3px 10px",
    borderRadius: 20,
    fontWeight: 700,
  },
  chipVerde: {
    fontSize: 14,
    color: "var(--verde)",
    background: "var(--verde-bg)",
    border: "1.5px solid var(--verde)",
    borderRadius: 20,
    padding: "7px 14px",
    cursor: "pointer",
    fontWeight: 700,
    flexShrink: 0,
  },
  estadoPedidoInfo: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    background: "#f8fafc",
    border: "1.5px solid #e2e8f0",
    borderRadius: 12,
    padding: "11px 13px",
    fontSize: 13,
    color: "#475569",
    marginBottom: 12,
    lineHeight: 1.35,
  },
  chipNoVoy: {
    fontSize: 13,
    color: "#b91c1c",
    background: "#fff5f5",
    border: "1.5px solid #fecaca",
    borderRadius: 20,
    padding: "8px 13px",
    minHeight: 36,
    cursor: "pointer",
    fontWeight: 700,
    flexShrink: 0,
  },
  chipNoVoySuave: {
    fontSize: 13,
    color: "#7f1d1d",
    background: "#fff",
    border: "1px solid #fecaca",
    borderRadius: 20,
    padding: "8px 13px",
    minHeight: 36,
    cursor: "pointer",
    fontWeight: 700,
    flexShrink: 0,
    opacity: 0.82,
  },
  separadorFijos: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    margin: "6px 0 10px",
  },
  separadorTexto: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--subtexto)",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    background: "#f8fafc",
    padding: "3px 10px",
    borderRadius: 6,
  },
  opcionBtn: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "14px 14px",
    minHeight: 52,
    borderRadius: 10,
    border: "1.5px solid var(--borde)",
    background: "#fff",
    textAlign: "left",
    width: "100%",
    cursor: "pointer",
  },
  badge: {
    fontSize: 12,
    background: "var(--verde)",
    color: "#fff",
    padding: "3px 9px",
    borderRadius: 20,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  inputNotas: {
    width: "100%",
    padding: "10px 13px",
    borderRadius: 9,
    border: "1.5px solid var(--borde)",
    fontSize: 15,
    boxSizing: "border-box",
  },
  stickyStepperWrap: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    background: "#f0f4f0",
    padding: "8px 14px 4px",
    margin: "0 -14px",
  },
  diasListWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    paddingBottom: 10,
  },
  sinServicioCard: {
    background: "#fff",
    borderRadius: 14,
    border: "2px solid var(--borde)",
    overflow: "hidden",
    opacity: 0.6,
  },
  sinServicioBody: { padding: "14px 16px" },
  sinServicioMeta: { color: "var(--subtexto)", fontSize: 13 },
  sinServicioTexto: { marginTop: 6, color: "var(--subtexto)", fontSize: 14 },
  footer: { marginTop: 16, padding: "0 0 16px", textAlign: "center" },
  footerFloat: {
    position: "fixed",
    bottom: 58,
    left: 0,
    right: 0,
    maxWidth: 560,
    margin: "0 auto",
    padding: "10px 14px",
    background: "rgba(248,250,248,0.97)",
    borderTop: "1px solid var(--borde)",
    backdropFilter: "blur(8px)",
    zIndex: 50,
  },
  footerEstado: {
    fontSize: 13,
    color: "#374151",
    fontWeight: 800,
    lineHeight: 1.35,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  footerEstadoWarning: { color: "#92400e" },
  btnEnviar: {
    background: "var(--verde)",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    padding: "14px 32px",
    fontSize: 17,
    fontWeight: 700,
    width: "100%",
    maxWidth: 400,
    cursor: "pointer",
  },
  btnSecundario: {
    background: "#fff",
    color: "var(--verde)",
    border: "2px solid var(--verde)",
    borderRadius: 12,
    padding: "12px 24px",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
  },
  footerError: {
    color: "var(--error)",
    fontSize: 12,
    marginTop: 4,
    textAlign: "center",
  },
};

export const sEstado = {
  loadingTexto: { textAlign: "center", padding: 60, color: "var(--subtexto)" },
  confirmadoLayout: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100%",
    paddingBottom: 90,
  },
  heroWrap: { textAlign: "center", padding: "36px 0 24px" },
  heroIconWrap: {
    width: 72,
    height: 72,
    borderRadius: "50%",
    background: "var(--verde)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  heroIcon: { fontSize: 36, color: "#fff", lineHeight: 1 },
  heroTitulo: {
    fontSize: 22,
    fontWeight: 800,
    color: "#111827",
    marginBottom: 4,
  },
  heroSub: { color: "var(--subtexto)", fontSize: 14 },
  heroMeta: { color: "var(--subtexto)", fontSize: 13, marginTop: 2 },
  resumenCard: {
    background: "#fff",
    borderRadius: 16,
    padding: "4px 0",
    marginBottom: 24,
    border: "1px solid var(--borde)",
  },
  resumenFila: { display: "flex", gap: 12, padding: "13px 18px" },
  resumenFilaBorde: { borderBottom: "1px solid var(--borde)" },
  resumenDia: {
    fontWeight: 700,
    minWidth: 82,
    fontSize: 14,
    color: "var(--verde)",
  },
  resumenContenido: { flex: 1 },
  resumenPlato: { fontWeight: 600, fontSize: 14 },
  resumenGuarnicion: { fontSize: 13, color: "var(--subtexto)", marginTop: 2 },
  resumenNotas: {
    fontSize: 12,
    color: "var(--subtexto)",
    fontStyle: "italic",
    marginTop: 2,
  },
  btnCancelarLink: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#dc2626",
    fontSize: 14,
    padding: "8px 0",
    textDecoration: "underline",
  },
  noMenuCard: {
    background: "#fff",
    border: "1.5px solid var(--borde)",
    borderRadius: 16,
    padding: "14px 16px 12px",
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
    overflow: "hidden",
  },
  loadingPedidoTexto: {
    textAlign: "center",
    padding: 40,
    color: "var(--subtexto)",
  },
};

export const sHome = {
  card: {
    background: "#fff",
    border: "1.5px solid var(--borde)",
    borderRadius: 16,
    padding: "14px 16px 12px",
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
    overflow: "hidden",
  },
  cardOk: { background: "#f0fdf4", border: "1.5px solid #86efac" },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
    flexShrink: 0,
  },
  cardIcono: { fontSize: 20, lineHeight: 1 },
  cardTitulo: { fontSize: 15, fontWeight: 800, lineHeight: 1.2 },
  cardSub: { fontSize: 12, marginTop: 2 },
  menuOpcion: { color: "#64748b", fontWeight: 600 },
  diasResumen: {
    display: "flex",
    flexDirection: "column",
    borderTop: "1px solid #e5e7eb",
    paddingTop: 6,
    flex: 1,
  },
  diaFila: {
    display: "flex",
    gap: 10,
    flex: 1,
    borderBottom: "1px solid #f3f4f6",
    alignItems: "center",
  },
  diaFilaSinVianda: { opacity: 0.5 },
  diaLabel: {
    fontWeight: 700,
    fontSize: 13,
    color: "#15803d",
    minWidth: 66,
    flexShrink: 0,
  },
  diaLabelSinVianda: { color: "#9ca3af" },
  diaPlato: { fontWeight: 600, fontSize: 14, color: "#1a1a1a" },
  diaGuarnicion: { fontSize: 12, color: "#4b7c5a" },
  diaSinVianda: { fontSize: 12, fontWeight: 600, color: "#9ca3af" },
  heroCerrado: {
    background: "#fff",
    border: "1.5px solid var(--borde)",
    borderRadius: 16,
    padding: "14px 16px 12px",
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
    overflow: "hidden",
  },
  noMenuCentro: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 8px",
  },
  noMenuMensaje: {
    fontSize: 14,
    fontWeight: 600,
    color: "#6b7280",
    textAlign: "center",
    lineHeight: 1.5,
  },
  btnAccion: {
    flexShrink: 0,
    width: "100%",
    marginTop: 10,
    border: "1.5px solid #3b82f6",
    background: "#fff",
    color: "#1d4ed8",
    borderRadius: 10,
    padding: "10px 16px",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
  },
  btnAccionOk: { borderColor: "#15803d", color: "#15803d" },
};

export const sG = {
  panel: {
    border: "1.5px solid var(--verde)",
    borderTop: "1px solid #c3dfc0",
    borderRadius: "0 0 10px 10px",
    background: "#fafffe",
    padding: "8px 14px 10px",
  },
  panelColapsado: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    border: "1.5px solid var(--verde)",
    borderTop: "1px solid #c3dfc0",
    borderRadius: "0 0 10px 10px",
    background: "var(--verde-bg)",
    padding: "7px 14px",
    cursor: "pointer",
    textAlign: "left",
  },
  label: {
    display: "block",
    fontSize: 12,
    fontWeight: 700,
    color: "#4a7c59",
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  chips: { display: "flex", flexWrap: "wrap", gap: 6 },
  chip: {
    padding: "6px 13px",
    borderRadius: 20,
    border: "1.5px solid #c3dfc0",
    background: "#fff",
    fontSize: 13,
    fontWeight: 500,
    color: "#374151",
    cursor: "pointer",
  },
  chipSel: {
    background: "var(--verde)",
    color: "#fff",
    border: "1.5px solid var(--verde)",
    fontWeight: 700,
  },
};
