import { Router } from 'express';
import healthRoutes from '../modules/health/health.routes.js';
import usersRoutes from '../modules/users/users.routes.js';
import platosRoutes from '../modules/platos/platos.routes.js';
import menusSemanalesRoutes from '../modules/menus-semanales/menus-semanales.routes.js';
import estadisticasRoutes from '../modules/estadisticas/estadisticas.routes.js';
import sugerenciasRoutes from '../modules/sugerencias/sugerencias.routes.js';
import pedidosRoutes from '../modules/pedidos/pedidos.routes.js';
import authRoutes from '../modules/auth/auth.routes.js';
import adminAuthRoutes from '../modules/admin-auth/admin-auth.routes.js';
import guarnicionesRoutes from '../modules/guarniciones/guarniciones.routes.js';
import salsasRoutes from '../modules/salsas/salsas.routes.js';
import empresasRoutes from '../modules/empresas/empresas.routes.js';
import empleadosRoutes from '../modules/empleados/empleados.routes.js';
import menuRoutes from '../modules/menu/menu.routes.js';
import notificacionesRoutes from '../modules/notificaciones/notificaciones.routes.js';
import adminAuditoriaRoutes from '../modules/admin-auditoria/admin-auditoria.routes.js';
import planesRoutes from '../modules/planes/planes.routes.js';
import finanzasRoutes from '../modules/finanzas/finanzas.routes.js';
import cocinaRoutes from '../modules/cocina/cocina.routes.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/admin/auth', adminAuthRoutes);
router.use('/admin/auditoria', adminAuditoriaRoutes);
router.use('/users', usersRoutes);
router.use('/platos', platosRoutes);
router.use('/menus-semanales', menusSemanalesRoutes);
router.use('/estadisticas', estadisticasRoutes);
router.use('/sugerencias', sugerenciasRoutes);
router.use('/pedidos', pedidosRoutes);
router.use('/menu', menuRoutes);
router.use('/guarniciones', guarnicionesRoutes);
router.use('/salsas', salsasRoutes);
router.use('/empresas', empresasRoutes);
router.use('/empleados', empleadosRoutes);
router.use('/planes', planesRoutes);
router.use('/notificaciones', notificacionesRoutes);
router.use('/finanzas', finanzasRoutes);
router.use('/cocina', cocinaRoutes);

export default router;
